/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.jeupirates;

import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author yannf
 */
public class MenuPanel extends javax.swing.JPanel {
    JFrame parentFrame;
    JPanel parentPanel;
    
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWithBackgroundMenu = new components.JPanelWithBackground();
        GameTitle = new javax.swing.JLabel();
        StartButton = new components.JButtonCustom();
        try{
            StartButton.setImage();
        }catch (IOException e){
            System.out.print("Button Icon Not found");
        }
        OptionButton = new components.JButtonCustom();
        try{
            OptionButton.setImage();
        }catch (IOException e){
            System.out.print("Button Icon Not found");
        }
        QuitButton = new components.JButtonCustom();
        try{
            QuitButton.setImage();
        }catch (IOException e){
            System.out.print("Button Icon Not found");
        }

        jPanelWithBackgroundMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        try{
            jPanelWithBackgroundMenu.setImage("ressources/pirates_background.png");
        }catch (IOException e) {
            String userDirectory = new File("").getAbsolutePath();
            System.out.print("Background not found"); // or handle the error
        }
        jPanelWithBackgroundMenu.repaint();

        GameTitle.setFont(new java.awt.Font("Windlass", 0, 48)); // NOI18N
        GameTitle.setText("Argonautes");

        StartButton.setBorder(null);
        StartButton.setText("Start");
        StartButton.setFont(new java.awt.Font("Windlass", 0, 12)); // NOI18N
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        OptionButton.setBorder(null);
        OptionButton.setText("Options");
        OptionButton.setFont(new java.awt.Font("Windlass", 0, 12)); // NOI18N
        OptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionButtonActionPerformed(evt);
            }
        });

        QuitButton.setBorder(null);
        QuitButton.setText("Quit");
        QuitButton.setFont(new java.awt.Font("Windlass", 0, 12)); // NOI18N
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelWithBackgroundMenuLayout = new javax.swing.GroupLayout(jPanelWithBackgroundMenu);
        jPanelWithBackgroundMenu.setLayout(jPanelWithBackgroundMenuLayout);
        jPanelWithBackgroundMenuLayout.setHorizontalGroup(
            jPanelWithBackgroundMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWithBackgroundMenuLayout.createSequentialGroup()
                .addContainerGap(371, Short.MAX_VALUE)
                .addGroup(jPanelWithBackgroundMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWithBackgroundMenuLayout.createSequentialGroup()
                        .addComponent(GameTitle)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWithBackgroundMenuLayout.createSequentialGroup()
                        .addGroup(jPanelWithBackgroundMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
        );
        jPanelWithBackgroundMenuLayout.setVerticalGroup(
            jPanelWithBackgroundMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWithBackgroundMenuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(GameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWithBackgroundMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWithBackgroundMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionButtonActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        // TODO add your handling code here:
        parentFrame.dispose();
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        //parentPanel.removeAll();
        //parentPanel.add(this)
    }//GEN-LAST:event_StartButtonActionPerformed


    public void setParents(JFrame parentFrame, JPanel parentPanel){
        this.parentFrame = parentFrame;
        this.parentPanel = parentPanel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameTitle;
    private components.JButtonCustom OptionButton;
    private components.JButtonCustom QuitButton;
    private components.JButtonCustom StartButton;
    private components.JPanelWithBackground jPanelWithBackgroundMenu;
    // End of variables declaration//GEN-END:variables
}
