/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jeupirates;

/**
 *
 * @author yannf
 */
public class Plateau extends javax.swing.JFrame {

    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZonePioche = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ZoneInfo = new javax.swing.JPanel();
        ZoneJeux = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ZonePioche.setBackground(new java.awt.Color(255, 153, 0));
        ZonePioche.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Pioche");
        ZonePioche.add(jLabel1, new java.awt.GridBagConstraints());

        getContentPane().add(ZonePioche, java.awt.BorderLayout.LINE_START);

        ZoneInfo.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout ZoneInfoLayout = new javax.swing.GroupLayout(ZoneInfo);
        ZoneInfo.setLayout(ZoneInfoLayout);
        ZoneInfoLayout.setHorizontalGroup(
            ZoneInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ZoneInfoLayout.setVerticalGroup(
            ZoneInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(ZoneInfo, java.awt.BorderLayout.LINE_END);

        ZoneJeux.setBackground(new java.awt.Color(204, 0, 255));

        javax.swing.GroupLayout ZoneJeuxLayout = new javax.swing.GroupLayout(ZoneJeux);
        ZoneJeux.setLayout(ZoneJeuxLayout);
        ZoneJeuxLayout.setHorizontalGroup(
            ZoneJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        ZoneJeuxLayout.setVerticalGroup(
            ZoneJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(ZoneJeux, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plateau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ZoneInfo;
    private javax.swing.JPanel ZoneJeux;
    private javax.swing.JPanel ZonePioche;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
